name: booktrackerv2
description: Tracker para livros
publish_to: 'none'

version: 6.0.7

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  easy_dynamic_theme: ^2.3.1
  animations: ^2.0.11
  cupertino_icons: ^1.0.0
  permission_handler: ^11.3.0
  dynamic_system_colors: ^1.8.0
  fluttertoast: ^8.2.12
  flutter_image_compress: ^2.4.0
  async_redux: ^25.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
